let myString: string;
let myNum: number;
let myBool: boolean;
let myVar: any;
let stringArray: string[];
let numberArray: number[];
let booleanArray: boolean[];
let stringArray_1: Array<string>;
let numberArray_1: Array<number>;
let booleanArray_1: Array<boolean>;
let stringNumTuple: [string, number];
myString = "hello there";
myNum = 22;
myBool = true;
myVar = "i can be anything";
stringArray = ["hello world", "goodbye world"];
numberArray = [2];
booleanArray = [true, false, true];
stringArray_1 = ["hi"];
numberArray_1 = [49];
booleanArray_1 = [true];
stringNumTuple = ["hi", 1];
let myVoid: void = null;
let myNull: null = null;
let myUndefined: undefined = undefined;
console.log(myString, myNum, myBool);
console.log(myVar);
console.log(stringArray, numberArray);
console.log(booleanArray);
console.log(stringArray_1);
console.log(numberArray_1);
console.log(booleanArray_1);
console.log(myVoid);
