var myString;
var myNum;
var myBool;
var myVar;
var stringArray;
var numberArray;
var booleanArray;
var stringArray_1;
var numberArray_1;
var booleanArray_1;
var stringNumTuple;
myString = "hello there";
myNum = 22;
myBool = true;
myVar = "i can be anything";
stringArray = ["hello world", "goodbye world"];
numberArray = [2];
booleanArray = [true, false, true];
stringArray_1 = ["hi"];
numberArray_1 = [49];
booleanArray_1 = [true];
stringNumTuple = ["hi", 1];
var myVoid = null;
var myNull = null;
var myUndefined = undefined;
// console.log(myString, myNum, myBool);
// console.log(myVar);
// console.log(stringArray, numberArray);
// console.log(booleanArray);
// console.log(stringArray_1);
// console.log(numberArray_1);
// console.log(booleanArray_1);
// console.log(myVoid);
